#!/bin/bash

if [ -z "$(podman ps --filter "name=postgres-shared" --format "{{.ID}}")" ]; then
    echo "Container postgres-shared not running. Exiting rallly-postgres-init.script..."
    exit
fi

if ! podman exec -t postgres-shared psql -U postgres -tXAc "SELECT 1 FROM pg_roles WHERE rolname='rallly'" | grep -q 1 ; then
    podman exec -t postgres-shared psql -U postgres -Xc "CREATE USER rallly WITH PASSWORD '{-{postgres_rallly_password}-}';"
fi

if ! podman exec -t postgres-shared psql -U postgres -tXAc "SELECT 1 FROM pg_database WHERE datname='rallly'" | grep -q 1 ; then
    podman exec -t postgres-shared psql -U postgres -Xc "CREATE DATABASE rallly OWNER rallly;"
fi
