#!/bin/bash

ADGUARD_CONF="$HOME/adguard/conf"
ADGUARD_CERTS="$HOME/adguard/conf/certs"
ADGUARD_WORK="$HOME/adguard/work"

for dir in "$ADGUARD_CONF" "$ADGUARD_WORK" "$ADGUARD_CERTS"; do
    mkdir -p "$dir"
    chmod 700 "$dir"
done

if [ -z "{-{adguard_cert_directory}-}" ] || [ -z "{-{adguard_cert_file}-}" ] || [ -z "{-{adguard_key_file}-}" ]; then
    echo "Adguard requires valid TLS certificates for DNS-over-TLS." >&2
    echo "Please provide values for adguard_path_to_key and adguard_path_to_cert in the quadlet_vars file." >&2
else
    cert="{-{adguard_cert_directory}-}/{-{adguard_cert_file}-}"
    key="{-{adguard_cert_directory}-}/{-{adguard_key_file}-}"
    owner_string="$(id -u):$(id -g)"
    for file in "$cert" "$key"; do
        target="$ADGUARD_CERTS/$(basename "$file")"
        test -e "$target" && continue
        echo "Copying $(basename $file) to AdGuard folder using sudo..." >&2
        sudo cp -v "$file" "$ADGUARD_CERTS/"
        sudo chown "$owner_string" "$target"
        chmod 600 "$target"
    done
fi
