#!/bin/bash

ADGUARD_CONF="$HOME/adguard/conf"
ADGUARD_CERTS="$HOME/adguard/conf/certs"
ADGUARD_WORK="$HOME/adguard/work"

for dir in "$ADGUARD_CONF" "$ADGUARD_WORK" "$ADGUARD_CERTS"; do
    mkdir -p "$dir"
    chmod 700 "$dir"
done

entry="dns.{-{hostname}-}:adguard-home.service" 
mapping_file="{-{HOME}-}/quadlet_certs/mappings"

mkdir -p "$(dirname "$mapping_file")"
touch "$mapping_file"
grep -Fq "$entry" "$mapping_file" && exit
echo "$entry" >> "$mapping_file"
